# File automatically-generated by STM32CubeMX - Do not modify
cmake_minimum_required(VERSION 3.22)
# STM32CubeMX generated symbols (macros)
set(MX_Defines_Syms 
	USE_HAL_DRIVER 
	STM32H7S7xx 
	USE_FULL_LL_DRIVER 
	USBPD_PORT_COUNT=1 
	_RTOS 
	_SRC 
	osCMSIS=0x20001U 
	USBPDCORE_LIB_NO_PD 
	TCPP0203_SUPPORT 
	USE_USB_HS
    $<$<CONFIG:Debug>:DEBUG>
)
# STM32CubeMX generated include paths
set(MX_Include_Dirs
    ${CMAKE_SOURCE_DIR}/Inc
    ${CMAKE_SOURCE_DIR}/../Drivers/BSP/STM32H7S78-DK
    ${CMAKE_SOURCE_DIR}/../Drivers/BSP/Components/tcpp0203
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Inc
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Inc/Legacy
    ${CMAKE_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/include
    ${CMAKE_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
    ${CMAKE_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
    ${CMAKE_SOURCE_DIR}/../Drivers/CMSIS/RTOS2/Include
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USBPD_Library/Core/inc
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USBPD_Library/Devices/STM32H7RSXX/inc
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Core/Inc
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Class/HID/Inc
    ${CMAKE_SOURCE_DIR}/../Drivers/CMSIS/Device/ST/STM32H7RSxx/Include
    ${CMAKE_SOURCE_DIR}/../Drivers/CMSIS/Include
)
# STM32CubeMX generated application sources
set(MX_Application_Src
    ${CMAKE_SOURCE_DIR}/Src/main.c
    ${CMAKE_SOURCE_DIR}/Src/freertos.c
    ${CMAKE_SOURCE_DIR}/Src/usbpd.c
    ${CMAKE_SOURCE_DIR}/Src/usbpd_dpm_user.c
    ${CMAKE_SOURCE_DIR}/Src/usbpd_dpm_core.c
    ${CMAKE_SOURCE_DIR}/Src/usbpd_pwr_user.c
    ${CMAKE_SOURCE_DIR}/Src/usbpd_pwr_if.c
    ${CMAKE_SOURCE_DIR}/Src/usbpd_usb_if.c
    ${CMAKE_SOURCE_DIR}/Src/usb_host.c
    ${CMAKE_SOURCE_DIR}/Src/usbh_conf.c
    ${CMAKE_SOURCE_DIR}/Src/usbh_platform.c
    ${CMAKE_SOURCE_DIR}/Src/stm32h7rsxx_it.c
    ${CMAKE_SOURCE_DIR}/Src/stm32h7rsxx_hal_msp.c
    ${CMAKE_SOURCE_DIR}/Src/stm32h7rsxx_hal_timebase_tim.c
    ${CMAKE_SOURCE_DIR}/Src/sysmem.c
    ${CMAKE_SOURCE_DIR}/Src/syscalls.c
    ${CMAKE_SOURCE_DIR}/Startup/startup_stm32h7s7xx.s
)

# STM32 HAL/LL Drivers
set(STM32_Drivers_Src
    ${CMAKE_SOURCE_DIR}/../Drivers/BSP/Components/tcpp0203/tcpp0203.c
    ${CMAKE_SOURCE_DIR}/../Drivers/BSP/Components/tcpp0203/tcpp0203_reg.c
    ${CMAKE_SOURCE_DIR}/../Drivers/BSP/STM32H7S78-DK/stm32h7s78_discovery.c
    ${CMAKE_SOURCE_DIR}/../Drivers/BSP/STM32H7S78-DK/stm32h7s78_discovery_bus.c
    ${CMAKE_SOURCE_DIR}/../Drivers/BSP/STM32H7S78-DK/stm32h7s78_discovery_usbpd_pwr.c
    ${CMAKE_SOURCE_DIR}/Src/system_stm32h7rsxx.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_tim.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_tim_ex.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_cortex.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_rcc.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_rcc_ex.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_flash.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_flash_ex.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_gpio.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_dma.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_dma_ex.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_pwr.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_pwr_ex.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_exti.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_rcc.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_exti.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_i2c.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_i2c_ex.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_smbus.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_smbus_ex.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_hcd.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_usb.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_utils.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_adc.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_adc_ex.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_uart.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_hal_uart_ex.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_ucpd.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_gpio.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_dma.c
    ${CMAKE_SOURCE_DIR}/../Drivers/STM32H7RSxx_HAL_Driver/Src/stm32h7rsxx_ll_tim.c
)

# Drivers Midllewares

set(STM32_USB_Host_Library_Src
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_core.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ctlreq.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_ioreq.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Core/Src/usbh_pipes.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/usbh_hid.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/usbh_hid_keybd.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/usbh_hid_mouse.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USB_Host_Library/Class/HID/Src/usbh_hid_parser.c
)
set(FreeRTOS_Src
    ${CMAKE_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/portable/Common/mpu_wrappers_v2.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/croutine.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/event_groups.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/list.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/queue.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/tasks.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/timers.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/portable/Common/mpu_wrappers.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c
)
set(STM32_USBPD_Library_Src
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USBPD_Library/Core/src/usbpd_trace.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USBPD_Library/Devices/STM32H7RSXX/src/usbpd_cad_hw_if.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USBPD_Library/Devices/STM32H7RSXX/src/usbpd_hw.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USBPD_Library/Devices/STM32H7RSXX/src/usbpd_hw_if_it.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USBPD_Library/Devices/STM32H7RSXX/src/usbpd_phy_hw_if.c
    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USBPD_Library/Devices/STM32H7RSXX/src/usbpd_pwr_hw_if.c
)
# Link directories setup
set(MX_LINK_DIRS

    ${CMAKE_SOURCE_DIR}/../Middlewares/ST/STM32_USBPD_Library/Core/lib
)
# Project libraries
set (MX_LINK_LIBS  
	:USBPDCORE_NOPD_CM7_wc32.a
    STM32_Drivers
    STM32_USB_Host_Library	FreeRTOS	STM32_USBPD_Library	
)
# Interface library for includes and symbols
add_library(stm32cubemx INTERFACE)
target_include_directories(stm32cubemx INTERFACE ${MX_Include_Dirs})
target_compile_definitions(stm32cubemx INTERFACE ${MX_Defines_Syms})

# Create STM32_Drivers static library
add_library(STM32_Drivers OBJECT)
target_sources(STM32_Drivers PRIVATE ${STM32_Drivers_Src})
target_link_libraries(STM32_Drivers PUBLIC stm32cubemx)

# Create STM32_USB_Host_Library static library
add_library(STM32_USB_Host_Library OBJECT)
target_sources(STM32_USB_Host_Library PRIVATE ${STM32_USB_Host_Library_Src})
target_link_libraries(STM32_USB_Host_Library PUBLIC stm32cubemx)

# Create FreeRTOS static library
add_library(FreeRTOS OBJECT)
target_sources(FreeRTOS PRIVATE ${FreeRTOS_Src})
target_link_libraries(FreeRTOS PUBLIC stm32cubemx)

# Create STM32_USBPD_Library static library
add_library(STM32_USBPD_Library OBJECT)
target_sources(STM32_USBPD_Library PRIVATE ${STM32_USBPD_Library_Src})
target_link_libraries(STM32_USBPD_Library PUBLIC stm32cubemx)


# Add STM32CubeMX generated application sources to the project
target_sources(${CMAKE_PROJECT_NAME} PRIVATE ${MX_Application_Src})

# Link directories setup
target_link_directories(${CMAKE_PROJECT_NAME} PRIVATE ${MX_LINK_DIRS})

# Add libraries to the project
target_link_libraries(${CMAKE_PROJECT_NAME} ${MX_LINK_LIBS})

# Add the map file to the list of files to be removed with 'clean' target
set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES ADDITIONAL_CLEAN_FILES ${CMAKE_PROJECT_NAME}.map)

# Validate that STM32CubeMX code is compatible with C standard
if((CMAKE_C_STANDARD EQUAL 90) OR (CMAKE_C_STANDARD EQUAL 99))
    message(ERROR "Generated code requires C11 or higher")
endif()